### ISSUE TITLE
Change to settings.json does not immediately change behavior/notify user

### ISSUE THREAD

**Issue by cshlatz** [Ichimonji10/killjoy#4]
In playing around with the current setup, I noticed that a change to the settings.json file has no effect on the behavior of Killjoy, nor does it inform the user that a change has been made.

It's worth mentioning that in Killjoy's current state, this has only applied when I gave the settings file a bogus notifier and restarted the program to an error.

Just the thoughts from an end user's perspective, depending on the final design decision regarding this:
- If the settings.json file can be changed on the fly, changes should actually take effect.
- If a restart is required, the user should be notified (or have the ability to setup a notification) that the settings file has changed and what actions are needed.

**Comment by Ichimonji10** [comment]
By default, I don't think that killjoy should automatically reload or restart upon detecting a new configuration file. The reason is consistency: every major daemon I've worked with reloads or restarts only when asked to, and doing what everyone else does lets killjoy follow the principle of least surprise.

I can imagine adding an `--auto-reload` flag or something similar that would cause killjoy to watch the settings file and reload (as if a SIGHUP was received) when it changes. It might be useful for development. But there's already general-purpose tools that provide this functionality, like [entr](http://eradman.com/entrproject/), and they do a really good job of handling the weird edge cases in that problem domain.

There are some ways that killjoy can do a better job of handling settings files, though.

First, the `killjoy settings validate` subcommand can be expanded. It currently checks the validity of whatever file killjoy would use when next starting. In other words, it typically checks the validity of `~/.config/killjoy/settings.json`. It would be nice if the subcommand could be told to validate a non-default configuration file, like `killjoy settings validate path/to/settings.json`.

Second, killjoy doesn't handle the SIGHUP signal. It would be nice if it did. The SIGHUP signal is typically interpreted as meaning "I will reload my configuration, and abort if it has any problems."

For a good example of a well-behaved and typical daemon, see nginx:

* `nginx -t` causes nginx to test its default config file.
* `nginx -t -c path/to/config.conf` causes nginx to test `path/to/config.conf`.
* The SIGHUP signal causes nginx to "Reload configuration, start the new worker process with a new configuration, and gracefully shut down old worker processes."

**Comment by Ichimonji10** [comment]
Closing in favor of the issues linked to above.
